// Listings data for Zero accommodation platform
export const LISTINGS = [
  /* ---- TREEHOUSES ---- */
  {
    id: 1,
    category: 'treehouse',
    culture: null,
    title: 'The Canopy Nest',
    location: 'Knysna Forest, Western Cape',
    price: 1850,
    rating: 4.97,
    reviews: 134,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: 'Treehouse',
    img: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
    amenities: ['WiFi', 'Kitchen', 'Parking', 'Outdoor shower', 'Fire pit', 'Deck'],
    description:
      'Nestled 9 metres above the forest floor in the heart of the Knysna Forest. Wake up to birdsong, sip your morning coffee on the private deck, and fall asleep to the sounds of the wild. This is pure freedom — no crowds, no noise, just you and the trees.',
    host: 'Thabo M.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Lerato K.',
        date: 'July 2026',
        stars: 5,
        text: 'Absolutely magical. We never wanted to leave. The deck at sunset is indescribable.',
      },
      {
        name: 'Marco V.',
        date: 'June 2026',
        stars: 5,
        text: 'Best stay of our lives. Thabo was incredibly welcoming and the space felt alive.',
      },
    ],
  },
  {
    id: 2,
    category: 'treehouse',
    culture: null,
    title: 'Sky Loft Hideaway',
    location: 'Magaliesberg, North West',
    price: 2100,
    rating: 4.91,
    reviews: 88,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: 'Treehouse',
    img: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=600&q=80',
    amenities: ['WiFi', 'Outdoor shower', 'Hammock', 'Fireplace', 'No TV by design', 'Stargazing deck'],
    description:
      'A romantic treehouse loft with floor-to-ceiling windows and a private stargazing deck. No TV, no distractions — just you, your person, and the Magaliesberg mountains. Completely off-grid solar powered.',
    host: 'Annika R.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Sipho D.',
        date: 'August 2026',
        stars: 5,
        text: 'We came for a weekend and wished we could stay a week. Truly otherworldly.',
      },
      {
        name: 'Priya N.',
        date: 'May 2026',
        stars: 4,
        text: 'Stunning views. A little hard to find but 100% worth it.',
      },
    ],
  },
  {
    id: 3,
    category: 'beach',
    culture: null,
    title: 'Sunset Shack Muizenberg',
    location: 'Muizenberg, Cape Town',
    price: 950,
    rating: 4.88,
    reviews: 201,
    guests: 4,
    beds: 2,
    baths: 1,
    badge: 'Beach',
    img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    amenities: ['WiFi', 'Kitchen', 'Beach gear', 'Outdoor shower', 'Surfboard rental', 'Braai area'],
    description:
      'Steps from the most colourful beach huts in the country. Surf, swim, eat fish and chips on the promenade — then come back to this cosy 2-bed shack that feels like the ocean itself lives inside. Perfect for friend groups and families.',
    host: 'Candice F.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Amos T.',
        date: 'August 2026',
        stars: 5,
        text: 'The location is unreal. Woke up, grabbed a board, and walked straight to the waves.',
      },
      {
        name: 'Julia M.',
        date: 'July 2026',
        stars: 5,
        text: 'Candice is the most generous host. Left us fresh produce from the market. Loved it.',
      },
    ],
  },
  {
    id: 4,
    category: 'beach',
    culture: null,
    title: 'Dune House Sodwana',
    location: 'Sodwana Bay, KwaZulu-Natal',
    price: 750,
    rating: 4.79,
    reviews: 63,
    guests: 6,
    beds: 3,
    baths: 2,
    badge: 'Beach',
    img: 'https://images.unsplash.com/photo-1471922694854-ff1b63b20054?w=600&q=80',
    amenities: ['WiFi', 'Full kitchen', 'Parking', 'Pool', 'Dive gear storage', 'Air conditioning'],
    description:
      'Right next to the world-famous Sodwana diving spots. Three bedrooms, a private pool, and an outdoor kitchen built for big gatherings. This is the one you book for a legendary friend trip or family reunion.',
    host: 'Kagiso L.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Brett H.',
        date: 'June 2026',
        stars: 5,
        text: 'Dove every morning, braai every evening. Absolute perfection for a group holiday.',
      },
    ],
  },
  {
    id: 5,
    category: 'garage',
    culture: null,
    title: 'The Workshop Loft',
    location: 'Maboneng, Johannesburg',
    price: 1100,
    rating: 4.85,
    reviews: 157,
    guests: 3,
    beds: 2,
    baths: 1,
    badge: 'Garage Home',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    amenities: ['WiFi', 'Kitchen', 'Car bay (2 vehicles)', 'Workshop tools', 'Smart TV', 'Security'],
    description:
      "A converted industrial workshop in the heart of Maboneng. High ceilings, polished concrete floors, exposed brick — and space for 2 cars in your very own indoor bay. An architect's dream turned into a liveable masterpiece.",
    host: 'Deon V.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Naledi S.',
        date: 'July 2026',
        stars: 5,
        text: 'This place is something else. Felt like living in a magazine. Will be back.',
      },
      {
        name: 'James O.',
        date: 'June 2026',
        stars: 5,
        text: 'Brought my project car along — having the bay was everything. 10/10.',
      },
    ],
  },
  {
    id: 6,
    category: 'garage',
    culture: null,
    title: 'Steel & Timber Dwelling',
    location: 'Woodstock, Cape Town',
    price: 1350,
    rating: 4.93,
    reviews: 94,
    guests: 4,
    beds: 2,
    baths: 2,
    badge: 'Garage Home',
    img: 'https://images.unsplash.com/photo-1486304873000-235643847519?w=600&q=80',
    amenities: ['WiFi', 'Full kitchen', '3-car garage', 'Rooftop deck', 'Smart home system', 'EV charger'],
    description:
      'What used to be a commercial garage is now a stunning 2-storey live-work space. Rooftop deck with city mountain views, a chef\'s kitchen, and a 3-car secure garage. The EV charger is a bonus — arrive in style and leave recharged.',
    host: 'Yusuf A.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Chantal D.',
        date: 'August 2026',
        stars: 5,
        text: 'The rooftop at sunset with Table Mountain in the background — zero words.',
      },
    ],
  },
  {
    id: 7,
    category: 'baker',
    culture: null,
    title: 'The Flour & Flame Flat',
    location: 'Bree Street, Cape Town',
    price: 880,
    rating: 4.82,
    reviews: 112,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: "Baker's Apt",
    img: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
    amenities: ['Professional kitchen', 'Stand mixer', 'Proofing oven', 'Recipe library', 'WiFi', 'Market basket on arrival'],
    description:
      'Designed by and for people who love to bake. A professional-grade kitchen with a proofing oven, stand mixer, and a full recipe library. Wake up, head to the nearby market, come back and bake your heart out. Warm, homey, and full of the smell of possibility.',
    host: 'Miriam B.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Zara P.',
        date: 'July 2026',
        stars: 5,
        text: 'As a pastry chef, this was heaven. The proofing oven alone is worth every cent.',
      },
      {
        name: 'Thandi M.',
        date: 'June 2026',
        stars: 5,
        text: 'Baked sourdough every single morning. The kitchen is better than most restaurants.',
      },
    ],
  },
  {
    id: 8,
    category: 'baker',
    culture: null,
    title: 'Sweet Home Melville',
    location: 'Melville, Johannesburg',
    price: 720,
    rating: 4.76,
    reviews: 78,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: "Baker's Apt",
    img: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=600&q=80',
    amenities: ['Full kitchen', 'Baking station', 'WiFi', 'Garden access', 'Weekly farmers market nearby', 'Spice rack included'],
    description:
      'A cosy Melville cottage with a dedicated baking station, warm Joburg sunshine, and a lush garden to enjoy your creations. Homey, relaxed, and built for the baker who wants to slow down and just create.',
    host: 'Rachel G.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Kwame S.',
        date: 'May 2026',
        stars: 4,
        text: 'Loved the garden. Made croissants and ate them outside. Pure joy.',
      },
    ],
  },
  {
    id: 9,
    category: 'musician',
    culture: null,
    title: 'The Resonance Studio',
    location: 'Newtown, Johannesburg',
    price: 1600,
    rating: 4.95,
    reviews: 67,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: 'Studio',
    img: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&q=80',
    amenities: ['Soundproofed', 'Recording booth', 'DAW workstation', 'Acoustic treatment', 'WiFi', 'Keyboard & guitar provided'],
    description:
      "A fully soundproofed live-in studio in Newtown — Jozi's creative heartbeat. Record during the day, sleep in the loft above at night. A DAW workstation with industry software, an acoustic booth, and a keyboard and guitar waiting for you.",
    host: 'Sipho K.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Leila A.',
        date: 'August 2026',
        stars: 5,
        text: 'Recorded an entire EP here. The acoustics are professional grade. Sipho is a legend.',
      },
      {
        name: 'David N.',
        date: 'July 2026',
        stars: 5,
        text: 'Cannot believe a place like this exists on Zero. Booked again already.',
      },
    ],
  },
  {
    id: 10,
    category: 'musician',
    culture: null,
    title: 'Salt River Sound Loft',
    location: 'Salt River, Cape Town',
    price: 1250,
    rating: 4.88,
    reviews: 43,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: 'Studio',
    img: 'https://images.unsplash.com/photo-1478737270197-f5b9e9e3a7d6?w=600&q=80',
    amenities: ['Soundproofed', 'Piano', 'Drum pad', 'Mixing board', 'WiFi', 'Rooftop access'],
    description:
      'A warm industrial loft that doubles as a creative music space. Piano, drum pads, mixing board — everything you need to get into the zone. Rooftop access for when you need fresh air between sessions.',
    host: 'Fatima S.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Marcus T.',
        date: 'June 2026',
        stars: 5,
        text: 'The piano alone had me in tears. A truly inspired space.',
      },
    ],
  },
  {
    id: 11,
    category: 'gamer',
    culture: null,
    title: 'Level Up Bunker',
    location: 'Hatfield, Pretoria',
    price: 650,
    rating: 4.84,
    reviews: 189,
    guests: 4,
    beds: 2,
    baths: 1,
    badge: 'Gamer Den',
    img: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&q=80',
    amenities: ['4K gaming setups (x4)', 'PS5 & Xbox Series X', 'VR headset', '120" projector', 'WiFi 1Gbps', 'Mini fridge & snack bar'],
    description:
      "The ultimate gamer's den. Four 4K gaming setups, a PS5, Xbox Series X, a VR headset, and a 120-inch projector for those big-screen moments. 1Gbps WiFi, a snack bar stocked on arrival, and blackout blinds. You may never leave.",
    host: 'Bryan X.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Itumeleng P.',
        date: 'July 2026',
        stars: 5,
        text: '48 hours of pure gaming bliss. The VR setup is next level. Already rebooked.',
      },
      {
        name: 'Shane W.',
        date: 'June 2026',
        stars: 5,
        text: 'Best bro trip we\'ve ever had. The projector for FIFA tournaments was ELITE.',
      },
    ],
  },
  {
    id: 12,
    category: 'gamer',
    culture: null,
    title: 'Respawn Retreat',
    location: 'Fourways, Johannesburg',
    price: 780,
    rating: 4.79,
    reviews: 102,
    guests: 3,
    beds: 2,
    baths: 1,
    badge: 'Gamer Den',
    img: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&q=80',
    amenities: ['3x Gaming PCs', 'Console corner', 'Streaming setup', 'Ring light & mic', 'WiFi 500Mbps', 'Smart lighting'],
    description:
      'Built for the modern gamer and streamer. Three gaming PCs, a full streaming corner with ring light and professional mic, and smart RGB lighting you control. Create content, go live, or just grind — this place was made for it.',
    host: 'Nadia C.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Rory M.',
        date: 'August 2026',
        stars: 5,
        text: 'Streamed to 5k viewers from here. The setup is legitimately professional.',
      },
    ],
  },
  {
    id: 13,
    category: 'japanese',
    culture: 'japanese',
    title: 'Zen Garden Retreat',
    location: 'Franschhoek, Western Cape',
    price: 2400,
    rating: 4.98,
    reviews: 76,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: 'Japanese',
    img: 'https://images.unsplash.com/photo-1545579133-99bb5ad189be?w=600&q=80',
    amenities: ['Tatami room', 'Private onsen', 'Zen garden', 'Tea ceremony kit', 'WiFi', 'Shoji sliding doors'],
    description:
      'A fully authentic Japanese-inspired retreat. Tatami floors, shoji screens, a private onsen (hot spring bath), and a hand-raked zen garden. Every detail sourced with care. Arrive stressed, leave transformed.',
    host: 'Aiko T.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Nomsa B.',
        date: 'July 2026',
        stars: 5,
        text: 'The onsen experience alone justifies the price. I cried when we had to leave.',
      },
      {
        name: 'Pierre L.',
        date: 'June 2026',
        stars: 5,
        text: 'Most peaceful place I\'ve ever stayed. Aiko\'s attention to detail is extraordinary.',
      },
    ],
  },
  {
    id: 14,
    category: 'japanese',
    culture: 'japanese',
    title: 'Sakura Studio',
    location: 'Gardens, Cape Town',
    price: 1400,
    rating: 4.89,
    reviews: 55,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: 'Japanese',
    img: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&q=80',
    amenities: ['Futon bedding', 'Bonsai collection', 'Tea station', 'WiFi', 'Japanese breakfast provided', 'Minimalist design'],
    description:
      'A minimalist Cape Town studio infused with Japanese aesthetics. Futon bedding, a curated bonsai collection, a morning matcha station, and a Japanese-style breakfast on arrival. Small in size, limitless in peace.',
    host: 'Kenji M.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Sara F.',
        date: 'August 2026',
        stars: 5,
        text: 'The morning matcha and bonsai corner set the tone for the most calming weekend.',
      },
    ],
  },
  {
    id: 15,
    category: 'korean',
    culture: 'korean',
    title: 'Seoul Hanok Hideout',
    location: 'Braamfontein, Johannesburg',
    price: 1700,
    rating: 4.92,
    reviews: 48,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: 'Korean',
    img: 'https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=600&q=80',
    amenities: ['Ondol floor heating', 'Jjimjilbang-style spa', 'Korean skincare station', 'WiFi', 'K-drama room', 'Korean breakfast'],
    description:
      'Inspired by traditional Korean hanok architecture. Ondol underfloor heating, a jjimjilbang-style relaxation room, a full Korean skincare station, and a K-drama lounge stocked with snacks and blankets. This one is for the culture.',
    host: 'Ji-Yeon P.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Lebo M.',
        date: 'July 2026',
        stars: 5,
        text: 'The K-drama room with the snack wall had us staying in all weekend on purpose.',
      },
      {
        name: 'Anna K.',
        date: 'June 2026',
        stars: 5,
        text: 'Ji-Yeon made us feel like family. The skincare station was an unexpected delight.',
      },
    ],
  },
  {
    id: 16,
    category: 'korean',
    culture: 'korean',
    title: 'Gangnam Style Flat',
    location: 'Sandton, Johannesburg',
    price: 2000,
    rating: 4.85,
    reviews: 37,
    guests: 2,
    beds: 1,
    baths: 1,
    badge: 'Korean',
    img: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    amenities: ['Smart toilet', 'Karaoke room', 'K-food pantry', 'WiFi', 'OLED TV wall', 'City views'],
    description:
      "Sleek, modern, and inspired by Seoul's glamorous Gangnam district. Smart toilet, a private karaoke room, OLED TV wall, and a K-food pantry stocked with everything from ramen to tteokbokki. City views on the 18th floor.",
    host: 'Min-Jae L.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Tshepo N.',
        date: 'August 2026',
        stars: 5,
        text: 'We did karaoke till 2am and the views were unreal. Worth every single rand.',
      },
    ],
  },
  {
    id: 17,
    category: 'southafrican',
    culture: 'southafrican',
    title: 'Ubuntu Lodge',
    location: 'Soweto, Johannesburg',
    price: 600,
    rating: 4.97,
    reviews: 223,
    guests: 6,
    beds: 3,
    baths: 2,
    badge: 'South African',
    img: 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=600&q=80',
    amenities: ['Braai pit', 'Township tour included', 'Shebeen corner', 'WiFi', 'African art collection', 'Marimba corner'],
    description:
      'A bold, colourful lodge celebrating the spirit of ubuntu — "I am because we are." Township-style décor, a shebeen corner stocked with local craft beer, a braai pit for epic evenings, and a marimba corner for impromptu sessions. A township tour is included on arrival.',
    host: 'Mama Rose',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Michael S.',
        date: 'July 2026',
        stars: 5,
        text: 'The most authentic South African experience I\'ve ever had. Mama Rose is a national treasure.',
      },
      {
        name: 'Claire B.',
        date: 'June 2026',
        stars: 5,
        text: 'The braai, the marimba, the art — it all moved me. I sobbed happy tears leaving.',
      },
    ],
  },
  {
    id: 18,
    category: 'southafrican',
    culture: 'southafrican',
    title: 'Karoo Farmstay',
    location: 'Matjiesfontein, Northern Cape',
    price: 850,
    rating: 4.91,
    reviews: 98,
    guests: 8,
    beds: 4,
    baths: 3,
    badge: 'South African',
    img: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f11?w=600&q=80',
    amenities: ['Stargazing deck', 'Braai', 'Farm animals', 'WiFi (limited — by design)', 'Outdoor kitchen', 'Boreholes & windmill'],
    description:
      'A sprawling Karoo farmstay under the darkest, most star-filled skies in the country. Four bedrooms, an outdoor kitchen, real farm animals, and a braai built for twelve. No signal struggles — that\'s the point. Disconnect to reconnect.',
    host: 'Dirk & Elsa V.',
    hostEmoji: '',
    reviewsList: [
      {
        name: 'Bongani Z.',
        date: 'August 2026',
        stars: 5,
        text: 'The Milky Way from that deck changed my perspective on life. I\'m serious.',
      },
      {
        name: 'Hanna T.',
        date: 'June 2026',
        stars: 5,
        text: 'Brought 7 friends. Best. Decision. Ever. Dirk\'s lamb chops on the braai — a religious experience.',
      },
    ],
  },
];
